#!/bin/bash

# Copyright 2012-2014  Brno University of Technology (Author: Karel Vesely)
# Apache 2.0

# This example script trains a DNN on top of fMLLR features. 
# The training is done in 3 stages,
#
# 1) RBM pre-training:
#    in this unsupervised stage we train stack of RBMs, 
#    a good starting point for frame cross-entropy trainig.
# 2) frame cross-entropy training:
#    the objective is to classify frames to correct pdfs.
# 3) sequence-training optimizing sMBR: 
#    the objective is to emphasize state-sequences with better 
#    frame accuracy w.r.t. reference alignment.

if [ $# -ne 2 ]; then
   echo "Argument should be the Timit directory, see ../run.sh for example."
   exit 1;
fi
CV=$1
mono_tri=$2
. ./cmd.sh ## You'll want to change cmd.sh to something that will work on your system.
           ## This relates to the queue.

. ./path.sh ## Source the tools/utils (import the queue.pl)

# Config:
gmmdir=$CV/exp/$mono_tri
#data_fmllr=$CV/data_delta
data_fmllr=$CV/data_fmllr
stage=0 # resume training with --stage=N
# End of config.
. utils/parse_options.sh || exit 1;
#

if [ $stage -le 0 ]; then
  # Store fMLLR features, so we can train on them easily,
  # test

	#dir=$data_fmllr/test
  #steps/nnet/make_delta_feats.sh --nj 4 --cmd "$train_cmd" \
  #   $dir $CV/data/test $gmmdir $dir/log $dir/data || exit 1 

	dir=$data_fmllr/test
  steps/nnet/make_fmllr_feats.sh --nj 4 --cmd "$train_cmd" \
    --transform-dir $CV/exp/$mono_tri/decode_test \
    $dir $CV/data/test $gmmdir $dir/log $dir/data || exit 1 
  # dev
#  dir=$data_fmllr/dev
#  steps/nnet/make_fmllr_feats.sh --nj 10 --cmd "$train_cmd" \
#     --transform-dir $gmmdir/decode_dev \
#     $dir data/dev $gmmdir $dir/log $dir/data || exit 1
  # train
  dir=$data_fmllr/train

	#steps/nnet/make_delta_feats.sh --nj 4 --cmd "$train_cmd" \
  #   $dir $CV/data/train $gmmdir $dir/log $dir/data || exit 1 

	steps/nnet/make_fmllr_feats.sh --nj 4 --cmd "$train_cmd" \
    --transform-dir $CV/exp/$mono_tri \
     $dir $CV/data/train $gmmdir $dir/log $dir/data || exit 1 

  # split the data : 90% train 10% cross-validation (held-out)
  utils/subset_data_dir_tr_cv.sh $dir ${dir}_tr90 ${dir}_cv10 || exit 1
fi

if [ $stage -le 1 ]; then
  # Pre-train DBN, i.e. a stack of RBMs (small database, smaller DNN)
  dir=$CV/exp/dnn4_pretrain-dbn
  (tail --pid=$$ -F $dir/log/pretrain_dbn.log 2>/dev/null)& # forward log
  $cuda_cmd $dir/log/pretrain_dbn.log \
    steps/nnet/pretrain_dbn.sh --nn-depth 6 --hid-dim 1024 --splice 5 --rbm-iter 10 $data_fmllr/train $dir || exit 1;
fi

if [ $stage -le 2 ]; then
  # Train the DNN optimizing per-frame cross-entropy.
	for x in `seq 6`; do
		dir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}_dnn$x
		ali=${gmmdir}_ali
		feature_transform=$CV/exp/dnn4_pretrain-dbn/final.feature_transform
		dbn=$CV/exp/dnn4_pretrain-dbn/${x}.dbn
		(tail --pid=$$ -F $dir/log/train_nnet.log 2>/dev/null)& # forward log
		# Train
		$cuda_cmd $dir/log/train_nnet.log \
			steps/nnet/train.sh --feature-transform $feature_transform --dbn $dbn --hid-layers 0 --learn-rate 0.008 \
			$data_fmllr/train_tr90 $data_fmllr/train_cv10 $CV/data/lang $ali $ali $dir || exit 1;
		# Decode (reuse HCLG graph)
		steps/nnet/decode.sh --nj 1 --cmd "$decode_cmd" --acwt 0.2 \
		  $gmmdir/graph $data_fmllr/test $dir/decode_test_dbn$x #|| exit 1;
	done
#  steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" --acwt 0.2 \
#    $gmmdir/graph $data_fmllr/dev $dir/decode_dev || exit 1;
fi
exit 0;

# Sequence training using sMBR criterion, we do Stochastic-GD 
# with per-utterance updates. We use usually good acwt 0.1
dir=exp/dnn4_pretrain-dbn_dnn_smbr
srcdir=exp/dnn4_pretrain-dbn_dnn
acwt=0.2

if [ $stage -le 3 ]; then
  # First we generate lattices and alignments:
  steps/nnet/align.sh --nj 4 --cmd "$train_cmd" \
    $data_fmllr/train data/lang $srcdir ${srcdir}_ali || exit 1;
  steps/nnet/make_denlats.sh --nj 4 --cmd "$decode_cmd" --acwt $acwt \
    --lattice-beam 10.0 --beam 18.0 \
    $data_fmllr/train data/lang $srcdir ${srcdir}_denlats || exit 1;
fi

if [ $stage -le 4 ]; then
  # Re-train the DNN by 6 iterations of sMBR 
  steps/nnet/train_mpe.sh --cmd "$cuda_cmd" --num-iters 3 --acwt $acwt \
    --do-smbr true --use-silphones true \
    $data_fmllr/train data/lang $srcdir ${srcdir}_ali ${srcdir}_denlats $dir || exit 1
  # Decode
  for ITER in 1 3; do
    steps/nnet/decode.sh --nj 1 --cmd "$decode_cmd" \
      --nnet $dir/${ITER}.nnet --acwt $acwt \
      $gmmdir/graph $data_fmllr/test $dir/decode_test_it${ITER} || exit 1
#    steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" \
#      --nnet $dir/${ITER}.nnet --acwt $acwt \
#      $gmmdir/graph $data_fmllr/dev $dir/decode_dev_it${ITER} || exit 1
  done 
fi

echo Success
exit 0

# Getting results [see RESULTS file]
# for x in exp/*/decode*; do [ -d $x ] && grep WER $x/wer_* | utils/best_wer.sh; done

#!/bin/bash

# Copyright 2012-2014  Brno University of Technology (Author: Karel Vesely)
# Apache 2.0

# This example script trains a DNN on top of fMLLR features. 
# The training is done in 3 stages,
#
# 1) RBM pre-training:
#    in this unsupervised stage we train stack of RBMs, 
#    a good starting point for frame cross-entropy trainig.
# 2) frame cross-entropy training:
#    the objective is to classify frames to correct pdfs.
# 3) sequence-training optimizing sMBR: 
#    the objective is to emphasize state-sequences with better 
#    frame accuracy w.r.t. reference alignment.

if [ $# -ne 3 ]; then
   echo "Argument should be the Timit directory, see ../run.sh for example."
   exit 1;
fi
CV=$1
mono_tri=$2
full_diag=$3

. ./cmd.sh ## You'll want to change cmd.sh to something that will work on your system.
           ## This relates to the queue.

. ./path.sh ## Source the tools/utils (import the queue.pl)

# Config:
gmmdir=$CV/exp/$mono_tri
#data_fmllr=$CV/data_delta
data_fmllr=$CV/$mono_tri/data_fmllr
stage=0 # resume training with --stage=N
train_nj=7
decode_nj=1
# End of config.
. utils/parse_options.sh || exit 1;
#

if [ $stage -le 0 ]; then
  # Store fMLLR features, so we can train on them easily,
  # test

	#dir=$data_fmllr/test
  #steps/nnet/make_delta_feats.sh --nj 4 --cmd "$train_cmd" \
  #   $dir $CV/data/test $gmmdir $dir/log $dir/data || exit 1 

	dir=$data_fmllr/test
  steps/nnet/make_basis_fmllr_feats.sh --nj $decode_nj --cmd "$train_cmd" \
    --transform-dir $CV/exp/$mono_tri/decode_test \
    $dir $CV/data/test $gmmdir $dir/log $dir/data || exit 1 
  # dev
#  dir=$data_fmllr/dev
#  steps/nnet/make_fmllr_feats.sh --nj 10 --cmd "$train_cmd" \
#     --transform-dir $gmmdir/decode_dev \
#     $dir data/dev $gmmdir $dir/log $dir/data || exit 1
  # train
  dir=$data_fmllr/train

	#steps/nnet/make_delta_feats.sh --nj 4 --cmd "$train_cmd" \
  #   $dir $CV/data/train $gmmdir $dir/log $dir/data || exit 1 

	steps/nnet/make_basis_fmllr_feats.sh --nj $train_nj --cmd "$train_cmd" \
    --transform-dir $CV/exp/$mono_tri \
     $dir $CV/data/train $gmmdir $dir/log $dir/data || exit 1 

  # split the data : 90% train 10% cross-validation (held-out)
  utils/subset_data_dir_tr_cv.sh $dir ${dir}_tr90 ${dir}_cv10 || exit 1
fi

if [ $stage -le 1 ]; then
  # Pre-train DBN, i.e. a stack of RBMs (small database, smaller DNN)
  dir=$CV/exp/dnn4_pretrain-dbn-$mono_tri
  (tail --pid=$$ -F $dir/log/pretrain_dbn.log 2>/dev/null)& # forward log
  $cuda_cmd $dir/log/pretrain_dbn.log \
    steps/nnet/pretrain_dbn.sh --nn-depth 6 --hid-dim 512 --splice 4 --rbm-iter 10 $data_fmllr/train $dir || exit 1;
fi

if [ $stage -le 2 ]; then
  # Train the DNN optimizing per-frame cross-entropy.
	for x in `seq 1 6`; do
		dir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}_dnn$x
  
    if [ $x == 1 ]; then
  		ali=${gmmdir}_ali
    else
      y=$((x-1))
      srcdir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}_dnn$y
      steps/nnet/align.sh --nj $train_nj --cmd "$train_cmd" \
      $data_fmllr/train $CV/data/lang $srcdir ${srcdir}_ali || exit 1;
      ali=${srcdir}_ali
    fi
		
		feature_transform=$CV/exp/dnn4_pretrain-dbn-$mono_tri/final.feature_transform
		dbn=$CV/exp/dnn4_pretrain-dbn-$mono_tri/${x}.dbn
		(tail --pid=$$ -F $dir/log/train_nnet.log 2>/dev/null)& # forward log
		# Train
		$cuda_cmd $dir/log/train_nnet.log \
			steps/nnet/train.sh --feature-transform $feature_transform --dbn $dbn --hid-layers 0 --learn-rate 0.008 \
			$data_fmllr/train_tr90 $data_fmllr/train_cv10 $CV/data/lang $ali $ali $dir || exit 1;
		# Decode (reuse HCLG graph)
		steps/nnet/decode.sh --nj $decode_nj --cmd "$decode_cmd" --acwt 0.2 \
		  $gmmdir/graph_bg $data_fmllr/test $dir/decode_test_dbn${x}_bg #|| exit 1;
		steps/nnet/decode.sh --nj $decode_nj --cmd "$decode_cmd" --acwt 0.2 \
		  $gmmdir/graph_tg $data_fmllr/test $dir/decode_test_dbn${x}_tg #|| exit 1;
	done
#  steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" --acwt 0.2 \
#    $gmmdir/graph $data_fmllr/dev $dir/decode_dev || exit 1;
fi
exit 0;

#!/bin/bash

# Copyright 2012-2014  Brno University of Technology (Author: Karel Vesely)
# Apache 2.0

# This example script trains a DNN on top of fMLLR features. 
# The training is done in 3 stages,
#
# 1) RBM pre-training:
#    in this unsupervised stage we train stack of RBMs, 
#    a good starting point for frame cross-entropy trainig.
# 2) frame cross-entropy training:
#    the objective is to classify frames to correct pdfs.
# 3) sequence-training optimizing sMBR: 
#    the objective is to emphasize state-sequences with better 
#    frame accuracy w.r.t. reference alignment.

if [ $# -ne 3 ]; then
   echo "Argument should be the Timit directory, see ../run.sh for example."
   exit 1;
fi
CV=$1
mono_tri=$2
full_diag=$3

. ./cmd.sh ## You'll want to change cmd.sh to something that will work on your system.
           ## This relates to the queue.

. ./path.sh ## Source the tools/utils (import the queue.pl)

# Config:
gmmdir=$CV/exp/$mono_tri
#data_fmllr=$CV/data_delta
data_fmllr=$CV/$mono_tri/data_fmllr
stage=0 # resume training with --stage=N
train_nj=7
decode_nj=1
# End of config.
. utils/parse_options.sh || exit 1;
#

if [ $stage -le 0 ]; then
  # Store fMLLR features, so we can train on them easily,
  # test

	#dir=$data_fmllr/test
  #steps/nnet/make_delta_feats.sh --nj 4 --cmd "$train_cmd" \
  #   $dir $CV/data/test $gmmdir $dir/log $dir/data || exit 1 

	dir=$data_fmllr/test
  steps/nnet/make_fmllr_feats.sh --nj $decode_nj --cmd "$train_cmd" \
    --transform-dir $CV/exp/$mono_tri/decode_test \
    $dir $CV/data/test $gmmdir $dir/log $dir/data || exit 1 
  # dev
#  dir=$data_fmllr/dev
#  steps/nnet/make_fmllr_feats.sh --nj 10 --cmd "$train_cmd" \
#     --transform-dir $gmmdir/decode_dev \
#     $dir data/dev $gmmdir $dir/log $dir/data || exit 1
  # train
  dir=$data_fmllr/train

	#steps/nnet/make_delta_feats.sh --nj 4 --cmd "$train_cmd" \
  #   $dir $CV/data/train $gmmdir $dir/log $dir/data || exit 1 

	steps/nnet/make_fmllr_feats.sh --nj $train_nj --cmd "$train_cmd" \
    --transform-dir $CV/exp/$mono_tri \
     $dir $CV/data/train $gmmdir $dir/log $dir/data || exit 1 

  # split the data : 90% train 10% cross-validation (held-out)
  utils/subset_data_dir_tr_cv.sh $dir ${dir}_tr90 ${dir}_cv10 || exit 1
fi

if [ $stage -le 1 ]; then
  # Pre-train DBN, i.e. a stack of RBMs (small database, smaller DNN)
  dir=$CV/exp/dnn4_pretrain-dbn-$mono_tri
  (tail --pid=$$ -F $dir/log/pretrain_dbn.log 2>/dev/null)& # forward log
  $cuda_cmd $dir/log/pretrain_dbn.log \
    steps/nnet/pretrain_dbn.sh --nn-depth 6 --hid-dim 512 --splice 4 --rbm-iter 10 $data_fmllr/train $dir || exit 1;
fi

if [ $stage -le 2 ]; then
  # Train the DNN optimizing per-frame cross-entropy.
	for x in `seq 1 6`; do
		dir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}_dnn$x
  
    if [ $x == 1 ]; then
  		ali=${gmmdir}_ali
    else
      y=$((x-1))
      srcdir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}_dnn$y
      steps/nnet/align.sh --nj $train_nj --cmd "$train_cmd" \
      $data_fmllr/train $CV/data/lang $srcdir ${srcdir}_ali || exit 1;
      ali=${srcdir}_ali
    fi
		
		feature_transform=$CV/exp/dnn4_pretrain-dbn-$mono_tri/final.feature_transform
		dbn=$CV/exp/dnn4_pretrain-dbn-$mono_tri/${x}.dbn
		(tail --pid=$$ -F $dir/log/train_nnet.log 2>/dev/null)& # forward log
		# Train
		$cuda_cmd $dir/log/train_nnet.log \
			steps/nnet/train.sh --feature-transform $feature_transform --dbn $dbn --hid-layers 0 --learn-rate 0.008 \
			$data_fmllr/train_tr90 $data_fmllr/train_cv10 $CV/data/lang $ali $ali $dir || exit 1;
		# Decode (reuse HCLG graph)
		steps/nnet/decode.sh --nj $decode_nj --cmd "$decode_cmd" --acwt 0.2 \
		  $gmmdir/graph_bg $data_fmllr/test $dir/decode_test_dbn${x}_bg #|| exit 1;
		steps/nnet/decode.sh --nj $decode_nj --cmd "$decode_cmd" --acwt 0.2 \
		  $gmmdir/graph_tg $data_fmllr/test $dir/decode_test_dbn${x}_tg #|| exit 1;
	done
#  steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" --acwt 0.2 \
#    $gmmdir/graph $data_fmllr/dev $dir/decode_dev || exit 1;
fi
exit 0;

#!/bin/bash

# Copyright 2012-2014  Brno University of Technology (Author: Karel Vesely)
# Apache 2.0

# This example script trains a DNN on top of fMLLR features. 
# The training is done in 3 stages,
#
# 1) RBM pre-training:
#    in this unsupervised stage we train stack of RBMs, 
#    a good starting point for frame cross-entropy trainig.
# 2) frame cross-entropy training:
#    the objective is to classify frames to correct pdfs.
# 3) sequence-training optimizing sMBR: 
#    the objective is to emphasize state-sequences with better 
#    frame accuracy w.r.t. reference alignment.

if [ $# -ne 2 ]; then
   echo "Argument should be the Timit directory, see ../run.sh for example."
   exit 1;
fi
CV=$1
mono_tri=$2
. ./cmd.sh ## You'll want to change cmd.sh to something that will work on your system.
           ## This relates to the queue.

. ./path.sh ## Source the tools/utils (import the queue.pl)

# Config:
gmmdir=$CV/exp/$mono_tri
data_fmllr=$CV/data_delta
stage=0 # resume training with --stage=N
train_nj=7
decode_nj=1
# End of config.
. utils/parse_options.sh || exit 1;
#

if [ $stage -le 0 ]; then
  # Store fMLLR features, so we can train on them easily,
  # test

	dir=$data_fmllr/test
  steps/nnet/make_delta_feats.sh --nj $decode_nj --cmd "$train_cmd" \
     $dir $CV/data/test $gmmdir $dir/log $dir/data || exit 1 

  # dev
#  dir=$data_fmllr/dev
#  steps/nnet/make_fmllr_feats.sh --nj 10 --cmd "$train_cmd" \
#     --transform-dir $gmmdir/decode_dev \
#     $dir data/dev $gmmdir $dir/log $dir/data || exit 1
  # train
  dir=$data_fmllr/train

	steps/nnet/make_delta_feats.sh --nj $train_nj --cmd "$train_cmd" \
     $dir $CV/data/train $gmmdir $dir/log $dir/data || exit 1 

  # split the data : 90% train 10% cross-validation (held-out)
  utils/subset_data_dir_tr_cv.sh $dir ${dir}_tr90 ${dir}_cv10 || exit 1
fi

if [ $stage -le 1 ]; then
  # Pre-train DBN, i.e. a stack of RBMs (small database, smaller DNN)
  dir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}
  (tail --pid=$$ -F $dir/log/pretrain_dbn.log 2>/dev/null)& # forward log
  $cuda_cmd $dir/log/pretrain_dbn.log \
    steps/nnet/pretrain_dbn.sh --nn-depth 6 --hid-dim 512 --splice 4 --rbm-iter 10 $data_fmllr/train $dir || exit 1;
fi

if [ $stage -le 2 ]; then
  # Train the DNN optimizing per-frame cross-entropy.
	for x in `seq 1 6`; do
		dir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}_dnn$x

    if [ $x == 1 ]; then
  		ali=${gmmdir}_ali
    else
      y=$((x-1))
      srcdir=$CV/exp/dnn4_pretrain-dbn-${mono_tri}_dnn$y
      steps/nnet/align.sh --nj $train_nj --cmd "$train_cmd" \
      $data_fmllr/train $CV/data/lang $srcdir ${srcdir}_ali || exit 1;
      ali=${srcdir}_ali
    fi

		feature_transform=$CV/exp/dnn4_pretrain-dbn-${mono_tri}/final.feature_transform
		dbn=$CV/exp/dnn4_pretrain-dbn-${mono_tri}/${x}.dbn
		(tail --pid=$$ -F $dir/log/train_nnet.log 2>/dev/null)& # forward log
		# Train
		$cuda_cmd $dir/log/train_nnet.log \
			steps/nnet/train.sh --feature-transform $feature_transform --dbn $dbn --hid-layers 0 --learn-rate 0.008 \
			$data_fmllr/train_tr90 $data_fmllr/train_cv10 $CV/data/lang $ali $ali $dir || exit 1;
		# Decode (reuse HCLG graph)
		steps/nnet/decode.sh --nj $decode_nj --cmd "$decode_cmd" --acwt 0.2 \
		  $gmmdir/graph_bg $data_fmllr/test $dir/decode_test_dbn${x}_bg #|| exit 1;
		steps/nnet/decode.sh --nj $decode_nj --cmd "$decode_cmd" --acwt 0.2 \
		  $gmmdir/graph_tg $data_fmllr/test $dir/decode_test_dbn${x}_tg #|| exit 1;
	done
#  steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" --acwt 0.2 \
#    $gmmdir/graph $data_fmllr/dev $dir/decode_dev || exit 1;
fi
exit 0;

# Sequence training using sMBR criterion, we do Stochastic-GD 
# with per-utterance updates. We use usually good acwt 0.1
dir=exp/dnn4_pretrain-dbn_dnn_smbr
srcdir=exp/dnn4_pretrain-dbn_dnn
acwt=0.2

if [ $stage -le 3 ]; then
  # First we generate lattices and alignments:
  steps/nnet/align.sh --nj 4 --cmd "$train_cmd" \
    $data_fmllr/train data/lang $srcdir ${srcdir}_ali || exit 1;
  steps/nnet/make_denlats.sh --nj 4 --cmd "$decode_cmd" --acwt $acwt \
    --lattice-beam 10.0 --beam 18.0 \
    $data_fmllr/train data/lang $srcdir ${srcdir}_denlats || exit 1;
fi

if [ $stage -le 4 ]; then
  # Re-train the DNN by 6 iterations of sMBR 
  steps/nnet/train_mpe.sh --cmd "$cuda_cmd" --num-iters 3 --acwt $acwt \
    --do-smbr true --use-silphones true \
    $data_fmllr/train data/lang $srcdir ${srcdir}_ali ${srcdir}_denlats $dir || exit 1
  # Decode
  for ITER in 1 3; do
    steps/nnet/decode.sh --nj 1 --cmd "$decode_cmd" \
      --nnet $dir/${ITER}.nnet --acwt $acwt \
      $gmmdir/graph $data_fmllr/test $dir/decode_test_it${ITER} || exit 1
#    steps/nnet/decode.sh --nj 20 --cmd "$decode_cmd" \
#      --nnet $dir/${ITER}.nnet --acwt $acwt \
#      $gmmdir/graph $data_fmllr/dev $dir/decode_dev_it${ITER} || exit 1
  done 
fi

echo Success
exit 0

# Getting results [see RESULTS file]
# for x in exp/*/decode*; do [ -d $x ] && grep WER $x/wer_* | utils/best_wer.sh; done
